### ISSUE TITLE
AttributeError: 'bool' object has no attribute '__call__'

### ISSUE THREAD

**Issue by IamMegatron2025** [realpython/flask-registration#5]
hello,after I `python manage.py runserver`, I get one error when I visit `localhost:5000`:

```
[2017-07-15 16:39:05,570] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ztgong/work/web/flask-registration/project/main/views.py", line 26, in home
    return render_template('main/index.html', current_user=current_user)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ztgong/.virtualenvs/flask-registration/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ztgong/work/web/flask-registration/project/templates/main/index.html", line 1, in top-level template code
    {% extends "_base.html" %}
  File "/home/ztgong/work/web/flask-registration/project/templates/_base.html", line 17, in top-level template code
    {% include "navigation.html" %}
  File "/home/ztgong/work/web/flask-registration/project/templates/navigation.html", line 19, in top-level template code
    {% elif current_user.is_authenticated() %}
AttributeError: 'bool' object has no attribute '__call__'
```

how to fix it?
thank you very much~

**Comment by IamMegatron2025** [comment]
use `current_user.is_authenticated` instead of `current_user.is_authenticated()`. see [url](https://github.com/lingthio/Flask-User-starter-app/issues/9)
